---
- name: Create users and assign them to appropriate groups
  hosts: server2
  become: yes
  tasks:

    - name: Ensure the groups exist
      group:
        name: "{{ item }}"
        state: present
      loop:
        - Sales
        - Support
        - Services
        - IT

    - name: Ensure users exist and are added to correct groups
      user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
        shell: /bin/bash
        ssh_authorized_keys: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK"
        password: "@#FD12"
      loop:
        - { name: Annabelle, groups: "Sales" }
        - { name: Bob, groups: "IT" }
        - { name: Carl, groups: "Support" }
        - { name: Dyson, groups: "Support" }
        - { name: Evert, groups: "IT" }
        - { name: Frank, groups: "Sales" }
        - { name: Gerry, groups: "Support" }
        - { name: Harold, groups: "IT" }
        - { name: Isabella, groups: "Services" }
        - { name: Jameson, groups: "Services" }

    - name: Set SSH key directory permissions
      file:
        path: "/home/{{ item.name }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
      loop:
        - { name: Annabelle }
        - { name: Bob }
        - { name: Carl }
        - { name: Dyson }
        - { name: Evert }
        - { name: Frank }
        - { name: Gerry }
        - { name: Harold }
        - { name: Isabella }
        - { name: Jameson }

    - name: Add SSH public key for users
      copy:
        content: "{{ item.ssh_key }}"
        dest: "/home/{{ item.name }}/.ssh/authorized_keys"
        mode: '0600'
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
      loop:
        - { name: Annabelle, ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK" }
        - { name: Bob, ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK" }
        - { name: Carl, ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK" }
        - { name: Dyson, ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK" }
        - { name: Evert, ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK" }
        - { name: Frank, ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK" }
        - { name: Gerry, ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK" }
        - { name: Harold, ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK" }
        - { name: Isabella, ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK" }
        - { name: Jameson, ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK" }
